---
- hosts: all
  gather_facts: True
  become: True
  vars_files:
    - "vars/default.yml"
    - "vars/secret.yml"
    #- "vars/secret-example.yml"
  roles:
    - requirements
    - customize
    - firewall