---
- name: Create a directory datastore if it does not exist
  ansible.builtin.file:
    path: /datastore
    state: directory
    mode: '0755'

- name: Add the user 'admin-local' with a primary group of 'root'
  ansible.builtin.user:
    name: admin-local
    comment: admin-local
    group: root