---
- name: Redhat
  include: requirements_rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Debian
  include: requirements_debian.yml
  when: ansible_os_family == "Debian"

- name: Research file "reboot_required"
  stat:
    path: /var/run/reboot-required
  register: __stat_reboot_required_file

- name: Reboot if necessary
  reboot:
    msg: "Reboot via ansible"
    connect_timeout: "{{ reboot_connect_timeout }}"
    reboot_timeout: "{{ reboot_timeout }}"
    pre_reboot_delay: "{{reboot_pre_reboot_delay}}"
    post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    test_command: uptime
  when: __stat_reboot_required_file.stat.exists