---
- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest

- name: Installation prerequisites
  dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: 
    - "{{ prerequis }}"
    - "{{ prerequis_rhel }}" 

