---
- name: Update repositories cache
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Installation prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ prerequis }}"